/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as AuthenticatedApplicationsRouteImport } from './routes/_authenticated/applications'
import { Route as AuthenticatedAssessmentsRouteImport } from './routes/_authenticated/assessments'
import { Route as AuthenticatedCertificatesRouteImport } from './routes/_authenticated/certificates'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedProjectsRouteImport } from './routes/_authenticated/projects'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AdminAdminIndexRouteImport } from './routes/_admin/admin.index'
import { Route as AdminAdminAnalyticsRouteImport } from './routes/_admin/admin.analytics'
import { Route as AdminAdminApplicantsRouteImport } from './routes/_admin/admin.applicants'
import { Route as AdminAdminAssessmentsRouteImport } from './routes/_admin/admin.assessments'
import { Route as AdminAdminAuditRouteImport } from './routes/_admin/admin.audit'
import { Route as AdminAdminCertificatesRouteImport } from './routes/_admin/admin.certificates'
import { Route as AdminAdminCohortsRouteImport } from './routes/_admin/admin.cohorts'
import { Route as AdminAdminCommunicationsRouteImport } from './routes/_admin/admin.communications'
import { Route as AdminAdminEmailsRouteImport } from './routes/_admin/admin.emails'
import { Route as AdminAdminInterviewsRouteImport } from './routes/_admin/admin.interviews'
import { Route as AdminAdminOffersRouteImport } from './routes/_admin/admin.offers'
import { Route as AdminAdminPipelineRouteImport } from './routes/_admin/admin.pipeline'
import { Route as AdminAdminProjectsRouteImport } from './routes/_admin/admin.projects'
import { Route as AdminAdminQuestionsRouteImport } from './routes/_admin/admin.questions'
import { Route as AdminAdminReportsRouteImport } from './routes/_admin/admin.reports'
import { Route as AdminAdminSearchRouteImport } from './routes/_admin/admin.search'
import { Route as AdminAdminSettingsRouteImport } from './routes/_admin/admin.settings'
import { Route as AdminAdminTracksRouteImport } from './routes/_admin/admin.tracks'
import { Route as AuthenticatedAssessmentsIdRouteImport } from './routes/_authenticated/assessments.$id'
import { Route as AdminAdminApplicantsIdRouteImport } from './routes/_admin/admin.applicants.$id'
import { Route as AdminAdminAssessmentsNewRouteImport } from './routes/_admin/admin.assessments.new'
import { Route as AdminAdminAssessmentsIdEditRouteImport } from './routes/_admin/admin.assessments.$id.edit'
import { Route as AuthenticatedAssessmentsIdAttemptAttemptIdRouteImport } from './routes/_authenticated/assessments.$id.attempt.$attemptId'
import { Route as AuthenticatedAssessmentsIdResultAttemptIdRouteImport } from './routes/_authenticated/assessments.$id.result.$attemptId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedApplicationsRoute =
  AuthenticatedApplicationsRouteImport.update({
    id: '/applications',
    path: '/applications',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAssessmentsRoute =
  AuthenticatedAssessmentsRouteImport.update({
    id: '/assessments',
    path: '/assessments',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCertificatesRoute =
  AuthenticatedCertificatesRouteImport.update({
    id: '/certificates',
    path: '/certificates',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProjectsRoute = AuthenticatedProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const AdminAdminIndexRoute = AdminAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminAnalyticsRoute = AdminAdminAnalyticsRouteImport.update({
  id: '/admin/analytics',
  path: '/admin/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminApplicantsRoute = AdminAdminApplicantsRouteImport.update({
  id: '/admin/applicants',
  path: '/admin/applicants',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminAssessmentsRoute = AdminAdminAssessmentsRouteImport.update({
  id: '/admin/assessments',
  path: '/admin/assessments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminAuditRoute = AdminAdminAuditRouteImport.update({
  id: '/admin/audit',
  path: '/admin/audit',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminCertificatesRoute = AdminAdminCertificatesRouteImport.update({
  id: '/admin/certificates',
  path: '/admin/certificates',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminCohortsRoute = AdminAdminCohortsRouteImport.update({
  id: '/admin/cohorts',
  path: '/admin/cohorts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminCommunicationsRoute =
  AdminAdminCommunicationsRouteImport.update({
    id: '/admin/communications',
    path: '/admin/communications',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminAdminEmailsRoute = AdminAdminEmailsRouteImport.update({
  id: '/admin/emails',
  path: '/admin/emails',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminInterviewsRoute = AdminAdminInterviewsRouteImport.update({
  id: '/admin/interviews',
  path: '/admin/interviews',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminOffersRoute = AdminAdminOffersRouteImport.update({
  id: '/admin/offers',
  path: '/admin/offers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminPipelineRoute = AdminAdminPipelineRouteImport.update({
  id: '/admin/pipeline',
  path: '/admin/pipeline',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminProjectsRoute = AdminAdminProjectsRouteImport.update({
  id: '/admin/projects',
  path: '/admin/projects',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminQuestionsRoute = AdminAdminQuestionsRouteImport.update({
  id: '/admin/questions',
  path: '/admin/questions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminReportsRoute = AdminAdminReportsRouteImport.update({
  id: '/admin/reports',
  path: '/admin/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminSearchRoute = AdminAdminSearchRouteImport.update({
  id: '/admin/search',
  path: '/admin/search',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminSettingsRoute = AdminAdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminTracksRoute = AdminAdminTracksRouteImport.update({
  id: '/admin/tracks',
  path: '/admin/tracks',
  getParentRoute: () => AdminRoute,
} as any)
const AuthenticatedAssessmentsIdRoute =
  AuthenticatedAssessmentsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAssessmentsRoute,
  } as any)
const AdminAdminApplicantsIdRoute = AdminAdminApplicantsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminAdminApplicantsRoute,
} as any)
const AdminAdminAssessmentsNewRoute =
  AdminAdminAssessmentsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AdminAdminAssessmentsRoute,
  } as any)
const AdminAdminAssessmentsIdEditRoute =
  AdminAdminAssessmentsIdEditRouteImport.update({
    id: '/$id/edit',
    path: '/$id/edit',
    getParentRoute: () => AdminAdminAssessmentsRoute,
  } as any)
const AuthenticatedAssessmentsIdAttemptAttemptIdRoute =
  AuthenticatedAssessmentsIdAttemptAttemptIdRouteImport.update({
    id: '/attempt/$attemptId',
    path: '/attempt/$attemptId',
    getParentRoute: () => AuthenticatedAssessmentsIdRoute,
  } as any)
const AuthenticatedAssessmentsIdResultAttemptIdRoute =
  AuthenticatedAssessmentsIdResultAttemptIdRouteImport.update({
    id: '/result/$attemptId',
    path: '/result/$attemptId',
    getParentRoute: () => AuthenticatedAssessmentsIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/verify': typeof VerifyRoute
  '/applications': typeof AuthenticatedApplicationsRoute
  '/assessments': typeof AuthenticatedAssessmentsRouteWithChildren
  '/certificates': typeof AuthenticatedCertificatesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/projects': typeof AuthenticatedProjectsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/admin/analytics': typeof AdminAdminAnalyticsRoute
  '/admin/applicants': typeof AdminAdminApplicantsRouteWithChildren
  '/admin/assessments': typeof AdminAdminAssessmentsRouteWithChildren
  '/admin/audit': typeof AdminAdminAuditRoute
  '/admin/certificates': typeof AdminAdminCertificatesRoute
  '/admin/cohorts': typeof AdminAdminCohortsRoute
  '/admin/communications': typeof AdminAdminCommunicationsRoute
  '/admin/emails': typeof AdminAdminEmailsRoute
  '/admin/interviews': typeof AdminAdminInterviewsRoute
  '/admin/offers': typeof AdminAdminOffersRoute
  '/admin/pipeline': typeof AdminAdminPipelineRoute
  '/admin/projects': typeof AdminAdminProjectsRoute
  '/admin/questions': typeof AdminAdminQuestionsRoute
  '/admin/reports': typeof AdminAdminReportsRoute
  '/admin/search': typeof AdminAdminSearchRoute
  '/admin/settings': typeof AdminAdminSettingsRoute
  '/admin/tracks': typeof AdminAdminTracksRoute
  '/assessments/$id': typeof AuthenticatedAssessmentsIdRouteWithChildren
  '/admin/': typeof AdminAdminIndexRoute
  '/admin/applicants/$id': typeof AdminAdminApplicantsIdRoute
  '/admin/assessments/new': typeof AdminAdminAssessmentsNewRoute
  '/admin/assessments/$id/edit': typeof AdminAdminAssessmentsIdEditRoute
  '/assessments/$id/attempt/$attemptId': typeof AuthenticatedAssessmentsIdAttemptAttemptIdRoute
  '/assessments/$id/result/$attemptId': typeof AuthenticatedAssessmentsIdResultAttemptIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/verify': typeof VerifyRoute
  '/applications': typeof AuthenticatedApplicationsRoute
  '/assessments': typeof AuthenticatedAssessmentsRouteWithChildren
  '/certificates': typeof AuthenticatedCertificatesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/projects': typeof AuthenticatedProjectsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/admin/analytics': typeof AdminAdminAnalyticsRoute
  '/admin/applicants': typeof AdminAdminApplicantsRouteWithChildren
  '/admin/assessments': typeof AdminAdminAssessmentsRouteWithChildren
  '/admin/audit': typeof AdminAdminAuditRoute
  '/admin/certificates': typeof AdminAdminCertificatesRoute
  '/admin/cohorts': typeof AdminAdminCohortsRoute
  '/admin/communications': typeof AdminAdminCommunicationsRoute
  '/admin/emails': typeof AdminAdminEmailsRoute
  '/admin/interviews': typeof AdminAdminInterviewsRoute
  '/admin/offers': typeof AdminAdminOffersRoute
  '/admin/pipeline': typeof AdminAdminPipelineRoute
  '/admin/projects': typeof AdminAdminProjectsRoute
  '/admin/questions': typeof AdminAdminQuestionsRoute
  '/admin/reports': typeof AdminAdminReportsRoute
  '/admin/search': typeof AdminAdminSearchRoute
  '/admin/settings': typeof AdminAdminSettingsRoute
  '/admin/tracks': typeof AdminAdminTracksRoute
  '/assessments/$id': typeof AuthenticatedAssessmentsIdRouteWithChildren
  '/admin': typeof AdminAdminIndexRoute
  '/admin/applicants/$id': typeof AdminAdminApplicantsIdRoute
  '/admin/assessments/new': typeof AdminAdminAssessmentsNewRoute
  '/admin/assessments/$id/edit': typeof AdminAdminAssessmentsIdEditRoute
  '/assessments/$id/attempt/$attemptId': typeof AuthenticatedAssessmentsIdAttemptAttemptIdRoute
  '/assessments/$id/result/$attemptId': typeof AuthenticatedAssessmentsIdResultAttemptIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteWithChildren
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/verify': typeof VerifyRoute
  '/_authenticated/applications': typeof AuthenticatedApplicationsRoute
  '/_authenticated/assessments': typeof AuthenticatedAssessmentsRouteWithChildren
  '/_authenticated/certificates': typeof AuthenticatedCertificatesRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/projects': typeof AuthenticatedProjectsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/_admin/admin/analytics': typeof AdminAdminAnalyticsRoute
  '/_admin/admin/applicants': typeof AdminAdminApplicantsRouteWithChildren
  '/_admin/admin/assessments': typeof AdminAdminAssessmentsRouteWithChildren
  '/_admin/admin/audit': typeof AdminAdminAuditRoute
  '/_admin/admin/certificates': typeof AdminAdminCertificatesRoute
  '/_admin/admin/cohorts': typeof AdminAdminCohortsRoute
  '/_admin/admin/communications': typeof AdminAdminCommunicationsRoute
  '/_admin/admin/emails': typeof AdminAdminEmailsRoute
  '/_admin/admin/interviews': typeof AdminAdminInterviewsRoute
  '/_admin/admin/offers': typeof AdminAdminOffersRoute
  '/_admin/admin/pipeline': typeof AdminAdminPipelineRoute
  '/_admin/admin/projects': typeof AdminAdminProjectsRoute
  '/_admin/admin/questions': typeof AdminAdminQuestionsRoute
  '/_admin/admin/reports': typeof AdminAdminReportsRoute
  '/_admin/admin/search': typeof AdminAdminSearchRoute
  '/_admin/admin/settings': typeof AdminAdminSettingsRoute
  '/_admin/admin/tracks': typeof AdminAdminTracksRoute
  '/_authenticated/assessments/$id': typeof AuthenticatedAssessmentsIdRouteWithChildren
  '/_admin/admin/': typeof AdminAdminIndexRoute
  '/_admin/admin/applicants/$id': typeof AdminAdminApplicantsIdRoute
  '/_admin/admin/assessments/new': typeof AdminAdminAssessmentsNewRoute
  '/_admin/admin/assessments/$id/edit': typeof AdminAdminAssessmentsIdEditRoute
  '/_authenticated/assessments/$id/attempt/$attemptId': typeof AuthenticatedAssessmentsIdAttemptAttemptIdRoute
  '/_authenticated/assessments/$id/result/$attemptId': typeof AuthenticatedAssessmentsIdResultAttemptIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/verify'
    | '/applications'
    | '/assessments'
    | '/certificates'
    | '/dashboard'
    | '/notifications'
    | '/profile'
    | '/projects'
    | '/settings'
    | '/auth/callback'
    | '/admin/analytics'
    | '/admin/applicants'
    | '/admin/assessments'
    | '/admin/audit'
    | '/admin/certificates'
    | '/admin/cohorts'
    | '/admin/communications'
    | '/admin/emails'
    | '/admin/interviews'
    | '/admin/offers'
    | '/admin/pipeline'
    | '/admin/projects'
    | '/admin/questions'
    | '/admin/reports'
    | '/admin/search'
    | '/admin/settings'
    | '/admin/tracks'
    | '/assessments/$id'
    | '/admin/'
    | '/admin/applicants/$id'
    | '/admin/assessments/new'
    | '/admin/assessments/$id/edit'
    | '/assessments/$id/attempt/$attemptId'
    | '/assessments/$id/result/$attemptId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/verify'
    | '/applications'
    | '/assessments'
    | '/certificates'
    | '/dashboard'
    | '/notifications'
    | '/profile'
    | '/projects'
    | '/settings'
    | '/auth/callback'
    | '/admin/analytics'
    | '/admin/applicants'
    | '/admin/assessments'
    | '/admin/audit'
    | '/admin/certificates'
    | '/admin/cohorts'
    | '/admin/communications'
    | '/admin/emails'
    | '/admin/interviews'
    | '/admin/offers'
    | '/admin/pipeline'
    | '/admin/projects'
    | '/admin/questions'
    | '/admin/reports'
    | '/admin/search'
    | '/admin/settings'
    | '/admin/tracks'
    | '/assessments/$id'
    | '/admin'
    | '/admin/applicants/$id'
    | '/admin/assessments/new'
    | '/admin/assessments/$id/edit'
    | '/assessments/$id/attempt/$attemptId'
    | '/assessments/$id/result/$attemptId'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/_authenticated'
    | '/auth'
    | '/verify'
    | '/_authenticated/applications'
    | '/_authenticated/assessments'
    | '/_authenticated/certificates'
    | '/_authenticated/dashboard'
    | '/_authenticated/notifications'
    | '/_authenticated/profile'
    | '/_authenticated/projects'
    | '/_authenticated/settings'
    | '/auth/callback'
    | '/_admin/admin/analytics'
    | '/_admin/admin/applicants'
    | '/_admin/admin/assessments'
    | '/_admin/admin/audit'
    | '/_admin/admin/certificates'
    | '/_admin/admin/cohorts'
    | '/_admin/admin/communications'
    | '/_admin/admin/emails'
    | '/_admin/admin/interviews'
    | '/_admin/admin/offers'
    | '/_admin/admin/pipeline'
    | '/_admin/admin/projects'
    | '/_admin/admin/questions'
    | '/_admin/admin/reports'
    | '/_admin/admin/search'
    | '/_admin/admin/settings'
    | '/_admin/admin/tracks'
    | '/_authenticated/assessments/$id'
    | '/_admin/admin/'
    | '/_admin/admin/applicants/$id'
    | '/_admin/admin/assessments/new'
    | '/_admin/admin/assessments/$id/edit'
    | '/_authenticated/assessments/$id/attempt/$attemptId'
    | '/_authenticated/assessments/$id/result/$attemptId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  VerifyRoute: typeof VerifyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/applications': {
      id: '/_authenticated/applications'
      path: '/applications'
      fullPath: '/applications'
      preLoaderRoute: typeof AuthenticatedApplicationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/assessments': {
      id: '/_authenticated/assessments'
      path: '/assessments'
      fullPath: '/assessments'
      preLoaderRoute: typeof AuthenticatedAssessmentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/certificates': {
      id: '/_authenticated/certificates'
      path: '/certificates'
      fullPath: '/certificates'
      preLoaderRoute: typeof AuthenticatedCertificatesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects': {
      id: '/_authenticated/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AuthenticatedProjectsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_admin/admin/': {
      id: '/_admin/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminAdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/analytics': {
      id: '/_admin/admin/analytics'
      path: '/admin/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/applicants': {
      id: '/_admin/admin/applicants'
      path: '/admin/applicants'
      fullPath: '/admin/applicants'
      preLoaderRoute: typeof AdminAdminApplicantsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/assessments': {
      id: '/_admin/admin/assessments'
      path: '/admin/assessments'
      fullPath: '/admin/assessments'
      preLoaderRoute: typeof AdminAdminAssessmentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/audit': {
      id: '/_admin/admin/audit'
      path: '/admin/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/certificates': {
      id: '/_admin/admin/certificates'
      path: '/admin/certificates'
      fullPath: '/admin/certificates'
      preLoaderRoute: typeof AdminAdminCertificatesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/cohorts': {
      id: '/_admin/admin/cohorts'
      path: '/admin/cohorts'
      fullPath: '/admin/cohorts'
      preLoaderRoute: typeof AdminAdminCohortsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/communications': {
      id: '/_admin/admin/communications'
      path: '/admin/communications'
      fullPath: '/admin/communications'
      preLoaderRoute: typeof AdminAdminCommunicationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/emails': {
      id: '/_admin/admin/emails'
      path: '/admin/emails'
      fullPath: '/admin/emails'
      preLoaderRoute: typeof AdminAdminEmailsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/interviews': {
      id: '/_admin/admin/interviews'
      path: '/admin/interviews'
      fullPath: '/admin/interviews'
      preLoaderRoute: typeof AdminAdminInterviewsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/offers': {
      id: '/_admin/admin/offers'
      path: '/admin/offers'
      fullPath: '/admin/offers'
      preLoaderRoute: typeof AdminAdminOffersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/pipeline': {
      id: '/_admin/admin/pipeline'
      path: '/admin/pipeline'
      fullPath: '/admin/pipeline'
      preLoaderRoute: typeof AdminAdminPipelineRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/projects': {
      id: '/_admin/admin/projects'
      path: '/admin/projects'
      fullPath: '/admin/projects'
      preLoaderRoute: typeof AdminAdminProjectsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/questions': {
      id: '/_admin/admin/questions'
      path: '/admin/questions'
      fullPath: '/admin/questions'
      preLoaderRoute: typeof AdminAdminQuestionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/reports': {
      id: '/_admin/admin/reports'
      path: '/admin/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminAdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/search': {
      id: '/_admin/admin/search'
      path: '/admin/search'
      fullPath: '/admin/search'
      preLoaderRoute: typeof AdminAdminSearchRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/settings': {
      id: '/_admin/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminAdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/tracks': {
      id: '/_admin/admin/tracks'
      path: '/admin/tracks'
      fullPath: '/admin/tracks'
      preLoaderRoute: typeof AdminAdminTracksRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_authenticated/assessments/$id': {
      id: '/_authenticated/assessments/$id'
      path: '/$id'
      fullPath: '/assessments/$id'
      preLoaderRoute: typeof AuthenticatedAssessmentsIdRouteImport
      parentRoute: typeof AuthenticatedAssessmentsRoute
    }
    '/_admin/admin/applicants/$id': {
      id: '/_admin/admin/applicants/$id'
      path: '/$id'
      fullPath: '/admin/applicants/$id'
      preLoaderRoute: typeof AdminAdminApplicantsIdRouteImport
      parentRoute: typeof AdminAdminApplicantsRoute
    }
    '/_admin/admin/assessments/new': {
      id: '/_admin/admin/assessments/new'
      path: '/new'
      fullPath: '/admin/assessments/new'
      preLoaderRoute: typeof AdminAdminAssessmentsNewRouteImport
      parentRoute: typeof AdminAdminAssessmentsRoute
    }
    '/_admin/admin/assessments/$id/edit': {
      id: '/_admin/admin/assessments/$id/edit'
      path: '/$id/edit'
      fullPath: '/admin/assessments/$id/edit'
      preLoaderRoute: typeof AdminAdminAssessmentsIdEditRouteImport
      parentRoute: typeof AdminAdminAssessmentsRoute
    }
    '/_authenticated/assessments/$id/attempt/$attemptId': {
      id: '/_authenticated/assessments/$id/attempt/$attemptId'
      path: '/attempt/$attemptId'
      fullPath: '/assessments/$id/attempt/$attemptId'
      preLoaderRoute: typeof AuthenticatedAssessmentsIdAttemptAttemptIdRouteImport
      parentRoute: typeof AuthenticatedAssessmentsIdRoute
    }
    '/_authenticated/assessments/$id/result/$attemptId': {
      id: '/_authenticated/assessments/$id/result/$attemptId'
      path: '/result/$attemptId'
      fullPath: '/assessments/$id/result/$attemptId'
      preLoaderRoute: typeof AuthenticatedAssessmentsIdResultAttemptIdRouteImport
      parentRoute: typeof AuthenticatedAssessmentsIdRoute
    }
  }
}

interface AdminAdminApplicantsRouteChildren {
  AdminAdminApplicantsIdRoute: typeof AdminAdminApplicantsIdRoute
}

const AdminAdminApplicantsRouteChildren: AdminAdminApplicantsRouteChildren = {
  AdminAdminApplicantsIdRoute: AdminAdminApplicantsIdRoute,
}

const AdminAdminApplicantsRouteWithChildren =
  AdminAdminApplicantsRoute._addFileChildren(AdminAdminApplicantsRouteChildren)

interface AdminAdminAssessmentsRouteChildren {
  AdminAdminAssessmentsNewRoute: typeof AdminAdminAssessmentsNewRoute
  AdminAdminAssessmentsIdEditRoute: typeof AdminAdminAssessmentsIdEditRoute
}

const AdminAdminAssessmentsRouteChildren: AdminAdminAssessmentsRouteChildren = {
  AdminAdminAssessmentsNewRoute: AdminAdminAssessmentsNewRoute,
  AdminAdminAssessmentsIdEditRoute: AdminAdminAssessmentsIdEditRoute,
}

const AdminAdminAssessmentsRouteWithChildren =
  AdminAdminAssessmentsRoute._addFileChildren(
    AdminAdminAssessmentsRouteChildren,
  )

interface AdminRouteChildren {
  AdminAdminAnalyticsRoute: typeof AdminAdminAnalyticsRoute
  AdminAdminApplicantsRoute: typeof AdminAdminApplicantsRouteWithChildren
  AdminAdminAssessmentsRoute: typeof AdminAdminAssessmentsRouteWithChildren
  AdminAdminAuditRoute: typeof AdminAdminAuditRoute
  AdminAdminCertificatesRoute: typeof AdminAdminCertificatesRoute
  AdminAdminCohortsRoute: typeof AdminAdminCohortsRoute
  AdminAdminCommunicationsRoute: typeof AdminAdminCommunicationsRoute
  AdminAdminEmailsRoute: typeof AdminAdminEmailsRoute
  AdminAdminInterviewsRoute: typeof AdminAdminInterviewsRoute
  AdminAdminOffersRoute: typeof AdminAdminOffersRoute
  AdminAdminPipelineRoute: typeof AdminAdminPipelineRoute
  AdminAdminProjectsRoute: typeof AdminAdminProjectsRoute
  AdminAdminQuestionsRoute: typeof AdminAdminQuestionsRoute
  AdminAdminReportsRoute: typeof AdminAdminReportsRoute
  AdminAdminSearchRoute: typeof AdminAdminSearchRoute
  AdminAdminSettingsRoute: typeof AdminAdminSettingsRoute
  AdminAdminTracksRoute: typeof AdminAdminTracksRoute
  AdminAdminIndexRoute: typeof AdminAdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdminAnalyticsRoute: AdminAdminAnalyticsRoute,
  AdminAdminApplicantsRoute: AdminAdminApplicantsRouteWithChildren,
  AdminAdminAssessmentsRoute: AdminAdminAssessmentsRouteWithChildren,
  AdminAdminAuditRoute: AdminAdminAuditRoute,
  AdminAdminCertificatesRoute: AdminAdminCertificatesRoute,
  AdminAdminCohortsRoute: AdminAdminCohortsRoute,
  AdminAdminCommunicationsRoute: AdminAdminCommunicationsRoute,
  AdminAdminEmailsRoute: AdminAdminEmailsRoute,
  AdminAdminInterviewsRoute: AdminAdminInterviewsRoute,
  AdminAdminOffersRoute: AdminAdminOffersRoute,
  AdminAdminPipelineRoute: AdminAdminPipelineRoute,
  AdminAdminProjectsRoute: AdminAdminProjectsRoute,
  AdminAdminQuestionsRoute: AdminAdminQuestionsRoute,
  AdminAdminReportsRoute: AdminAdminReportsRoute,
  AdminAdminSearchRoute: AdminAdminSearchRoute,
  AdminAdminSettingsRoute: AdminAdminSettingsRoute,
  AdminAdminTracksRoute: AdminAdminTracksRoute,
  AdminAdminIndexRoute: AdminAdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AuthenticatedAssessmentsIdRouteChildren {
  AuthenticatedAssessmentsIdAttemptAttemptIdRoute: typeof AuthenticatedAssessmentsIdAttemptAttemptIdRoute
  AuthenticatedAssessmentsIdResultAttemptIdRoute: typeof AuthenticatedAssessmentsIdResultAttemptIdRoute
}

const AuthenticatedAssessmentsIdRouteChildren: AuthenticatedAssessmentsIdRouteChildren =
  {
    AuthenticatedAssessmentsIdAttemptAttemptIdRoute:
      AuthenticatedAssessmentsIdAttemptAttemptIdRoute,
    AuthenticatedAssessmentsIdResultAttemptIdRoute:
      AuthenticatedAssessmentsIdResultAttemptIdRoute,
  }

const AuthenticatedAssessmentsIdRouteWithChildren =
  AuthenticatedAssessmentsIdRoute._addFileChildren(
    AuthenticatedAssessmentsIdRouteChildren,
  )

interface AuthenticatedAssessmentsRouteChildren {
  AuthenticatedAssessmentsIdRoute: typeof AuthenticatedAssessmentsIdRouteWithChildren
}

const AuthenticatedAssessmentsRouteChildren: AuthenticatedAssessmentsRouteChildren =
  {
    AuthenticatedAssessmentsIdRoute:
      AuthenticatedAssessmentsIdRouteWithChildren,
  }

const AuthenticatedAssessmentsRouteWithChildren =
  AuthenticatedAssessmentsRoute._addFileChildren(
    AuthenticatedAssessmentsRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedApplicationsRoute: typeof AuthenticatedApplicationsRoute
  AuthenticatedAssessmentsRoute: typeof AuthenticatedAssessmentsRouteWithChildren
  AuthenticatedCertificatesRoute: typeof AuthenticatedCertificatesRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedProjectsRoute: typeof AuthenticatedProjectsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedApplicationsRoute: AuthenticatedApplicationsRoute,
  AuthenticatedAssessmentsRoute: AuthenticatedAssessmentsRouteWithChildren,
  AuthenticatedCertificatesRoute: AuthenticatedCertificatesRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedProjectsRoute: AuthenticatedProjectsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  VerifyRoute: VerifyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
